import React from 'react'
import './globals.css'
import {
  Exo_2,
  Shadows_Into_Light_Two,
  Rubik_Moonrocks
} from 'next/font/google'
import { NavWrapper } from 'components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const exo2 = Exo_2({ subsets: ['latin'], variable: '--font-paragraph' })

const shadowsIntoLightTwo = Shadows_Into_Light_Two({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-heading'
})

const rubikMoonrocks = Rubik_Moonrocks({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-logo'
})

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`bg-background  ${exo2.variable} ${shadowsIntoLightTwo.variable} ${rubikMoonrocks.variable}`}
      >
        <NavWrapper>{children}</NavWrapper>
      </body>
    </html>
  )
}
