'use client'
import React from 'react'
import './globals.css'
import { SideMenu, Nav } from 'components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): JSX.Element {
  const [openMenu, setOpenMenu] = React.useState(false)
  return (
    <html lang="en">
      <body className="bg-background">
        <Nav setOpenMenu={setOpenMenu} />
        <SideMenu openMenu={openMenu} setOpenMenu={setOpenMenu} />
        {children}
      </body>
    </html>
  )
}
